/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['h1[_ngcontent-%COMP%] {\n    color: red;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2Nqb3JkYW5iYWxsL0Rlc2t0b3AvR2l0SHViUmVwb3MvVGhlLUNvbXBsZWF0LUFuZ3VsYXIvYXBwcy9zZWVkQXBwL3NyYy9hcHAvY29tcG9uZW50cy9hcHAvYXBwLmNvbXBvbmVudC5jc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvY2pvcmRhbmJhbGwvRGVza3RvcC9HaXRIdWJSZXBvcy9UaGUtQ29tcGxlYXQtQW5ndWxhci9hcHBzL3NlZWRBcHAvc3JjL2FwcC9jb21wb25lbnRzL2FwcC9hcHAuY29tcG9uZW50LmNzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
