/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './home.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './home.component';
const styles_HomeComponent:any[] = [i0.styles];
export const RenderType_HomeComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_HomeComponent,data:{}});
export function View_HomeComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted((null as any),['Home Page']))],(null as any),(null as any));
}
export function View_HomeComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-home',([] as any[]),
      (null as any),(null as any),(null as any),View_HomeComponent_0,RenderType_HomeComponent)),
      i1.ɵdid(49152,(null as any),0,i2.HomeComponent,([] as any[]),(null as any),(null as any))],
      (null as any),(null as any));
}
export const HomeComponentNgFactory:i1.ComponentFactory<i2.HomeComponent> = i1.ɵccf('app-home',
    i2.HomeComponent,View_HomeComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2Nqb3JkYW5iYWxsL0Rlc2t0b3AvR2l0SHViUmVwb3MvVGhlLUNvbXBsZWF0LUFuZ3VsYXIvYXBwcy9zZWVkQXBwL3NyYy9hcHAvY29tcG9uZW50cy9ob21lL2hvbWUuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2Nqb3JkYW5iYWxsL0Rlc2t0b3AvR2l0SHViUmVwb3MvVGhlLUNvbXBsZWF0LUFuZ3VsYXIvYXBwcy9zZWVkQXBwL3NyYy9hcHAvY29tcG9uZW50cy9ob21lL2hvbWUuY29tcG9uZW50LnRzIiwibmc6Ly8vVXNlcnMvY2pvcmRhbmJhbGwvRGVza3RvcC9HaXRIdWJSZXBvcy9UaGUtQ29tcGxlYXQtQW5ndWxhci9hcHBzL3NlZWRBcHAvc3JjL2FwcC9jb21wb25lbnRzL2hvbWUvaG9tZS5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL2Nqb3JkYW5iYWxsL0Rlc2t0b3AvR2l0SHViUmVwb3MvVGhlLUNvbXBsZWF0LUFuZ3VsYXIvYXBwcy9zZWVkQXBwL3NyYy9hcHAvY29tcG9uZW50cy9ob21lL2hvbWUuY29tcG9uZW50LnRzLkhvbWVDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8aDE+SG9tZSBQYWdlPC9oMT4iLCI8YXBwLWhvbWU+PC9hcHAtaG9tZT4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQSx3RUFBSTthQUFBOzs7b0JDQUo7TUFBQTthQUFBOzs7OyJ9
