/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './app.module';
import * as i2 from './components/app/app.component';
import * as i3 from './components/home/home.component.ngfactory';
import * as i4 from './components/app/app.component.ngfactory';
import * as i5 from '@angular/router';
import * as i6 from '@angular/common';
import * as i7 from './components/home/home.component';
import * as i8 from './app-routing.module';
export const AppModuleNgFactory:i0.NgModuleFactory<i1.AppModule> = i0.ɵcmf(i1.AppModule,
    [i2.AppComponent],(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i3.HomeComponentNgFactory,i4.AppComponentNgFactory]],[3,i0.ComponentFactoryResolver],
              i0.NgModuleRef]),i0.ɵmpd(5120,i5.ActivatedRoute,i5.ɵf,[i5.Router]),i0.ɵmpd(4608,
          i5.NoPreloading,i5.NoPreloading,([] as any[])),i0.ɵmpd(6144,i5.PreloadingStrategy,
          (null as any),[i5.NoPreloading]),i0.ɵmpd(135680,i5.RouterPreloader,i5.RouterPreloader,
          [i5.Router,i0.NgModuleFactoryLoader,i0.Compiler,i0.Injector,i5.PreloadingStrategy]),
          i0.ɵmpd(4608,i5.PreloadAllModules,i5.PreloadAllModules,([] as any[])),i0.ɵmpd(5120,
              i0.NgProbeToken,() => {
                return [i5.ɵb()];
              },([] as any[])),i0.ɵmpd(4608,i5.ɵg,i5.ɵg,[i0.Injector]),i0.ɵmpd(5120,
              i0.APP_INITIALIZER,(p0_0:any) => {
                return [i5.ɵh(p0_0)];
              },[i5.ɵg]),i0.ɵmpd(5120,i5.ROUTER_INITIALIZER,i5.ɵi,[i5.ɵg]),i0.ɵmpd(5120,
              i0.APP_BOOTSTRAP_LISTENER,(p0_0:any) => {
                return [p0_0];
              },[i5.ROUTER_INITIALIZER]),i0.ɵmpd(1024,i5.ɵa,i5.ɵd,[[3,i5.Router]]),
          i0.ɵmpd(512,i5.UrlSerializer,i5.DefaultUrlSerializer,([] as any[])),i0.ɵmpd(512,
              i5.ChildrenOutletContexts,i5.ChildrenOutletContexts,([] as any[])),i0.ɵmpd(256,
              i5.ROUTER_CONFIGURATION,{},([] as any[])),i0.ɵmpd(1024,i6.LocationStrategy,
              i5.ɵc,[i6.PlatformLocation,[2,i6.APP_BASE_HREF],i5.ROUTER_CONFIGURATION]),
          i0.ɵmpd(512,i6.Location,i6.Location,[i6.LocationStrategy]),i0.ɵmpd(512,i0.NgModuleFactoryLoader,
              i0.SystemJsNgModuleLoader,[i0.Compiler,[2,i0.SystemJsNgModuleLoaderConfig]]),
          i0.ɵmpd(1024,i5.ROUTES,() => {
            return [[{path:'',component:i7.HomeComponent}]];
          },([] as any[])),i0.ɵmpd(1024,i5.Router,i5.ɵe,[i0.ApplicationRef,i5.UrlSerializer,
              i5.ChildrenOutletContexts,i6.Location,i0.Injector,i0.NgModuleFactoryLoader,
              i0.Compiler,i5.ROUTES,i5.ROUTER_CONFIGURATION,[2,i5.UrlHandlingStrategy],
              [2,i5.RouteReuseStrategy]]),i0.ɵmpd(512,i5.RouterModule,i5.RouterModule,
              [[2,i5.ɵa],[2,i5.Router]]),i0.ɵmpd(512,i8.AppRoutingModule,i8.AppRoutingModule,
              ([] as any[])),i0.ɵmpd(512,i1.AppModule,i1.AppModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2Nqb3JkYW5iYWxsL0Rlc2t0b3AvR2l0SHViUmVwb3MvVGhlLUNvbXBsZWF0LUFuZ3VsYXIvYXBwcy9zZWVkQXBwL3NyYy9hcHAvYXBwLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9jam9yZGFuYmFsbC9EZXNrdG9wL0dpdEh1YlJlcG9zL1RoZS1Db21wbGVhdC1Bbmd1bGFyL2FwcHMvc2VlZEFwcC9zcmMvYXBwL2FwcC5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
